<?php echo '<?xml version="1.0" encoding="encoding"'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=encoding" />
<title>Insert title here</title>
</head>
<body>
<div>
	<?php echo $this->data->getUsername(); ?><br />
	<?php echo $this->data->getPassword(); ?><br />
	<?php echo $this->data->getLastLogin()->format('Y-m-d H:i:s'); ?><br />
	<?php echo $this->auth->hasIdentity(); ?><br />
	<?php print_r($this->auth->getIdentity()) ?><br />
</div>
</body>
</html>