<?php echo '<?xml version="1.0" encoding="encoding"'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=encoding" />
<title>Insert title here</title>
</head>
<body><?php 
/*@var $search kateglo\application\faces\Search */
$search = $this->search;
?>
<div>
	<form action="<?php echo $search->getFormAction(); ?>" method="<?php echo $search->getFormMethod();?>" >
		<div>
			<input type="text" name="<?php echo $search->getFieldName();?>" value="<?php echo $search->getFieldValue();?>"  />
			<input type="submit" name="<?php echo $search->getButtonName();?>" value="<?php echo $search->getButtonValue();?>" />
		</div> 
	</form>
</div>
</body>
</html>