<?php
namespace kateglo\proxies {
    /**
     * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
     */
    class kategloapplicationmodelsRelationTypeProxy extends \kateglo\application\models\RelationType implements \Doctrine\ORM\Proxy\Proxy {
        private $_entityPersister;
        private $_identifier;
        private $_loaded = false;
        public function __construct($entityPersister, $identifier) {
            $this->_entityPersister = $entityPersister;
            $this->_identifier = $identifier;
            parent::__construct();
        }
        private function _load() {
            if ( ! $this->_loaded) {
                $this->_entityPersister->load($this->_identifier, $this);
                unset($this->_entityPersister);
                unset($this->_identifier);
                $this->_loaded = true;
            }
        }
        public function __isInitialized__() { return $this->_loaded; }

        
        public function getId() {
            $this->_load();
            return parent::getId();
        }

        public function setType($type) {
            $this->_load();
            return parent::setType($type);
        }

        public function getType() {
            $this->_load();
            return parent::getType();
        }

        public function setAbbreviation($abbreviation) {
            $this->_load();
            return parent::setAbbreviation($abbreviation);
        }

        public function getAbbreviation() {
            $this->_load();
            return parent::getAbbreviation();
        }

        public function addRelation(\kateglo\application\models\Relation $relation) {
            $this->_load();
            return parent::addRelation($relation);
        }

        public function removeRelation(\kateglo\application\models\Relation $relation) {
            $this->_load();
            return parent::removeRelation($relation);
        }

        public function getRelations() {
            $this->_load();
            return parent::getRelations();
        }


        public function __sleep() {
            if (!$this->_loaded) {
                throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
            }
            return array('id', 'type', 'abbreviation', 'relations');
        }
    }
}