<?php
namespace kateglo\proxies {
    /**
     * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
     */
    class kategloapplicationmodelsPhraseAProxy extends \kateglo\application\models\Phrase implements \Doctrine\ORM\Proxy\Proxy {
        private $_em;
        private $_assoc;
        private $_owner;
        private $_joinColumnValues;
        private $_loaded = false;
        public function __construct($em, $assoc, $owner, array $joinColumnValues) {
            $this->_em = $em;
            $this->_assoc = $assoc;
            $this->_owner = $owner;
            $this->_joinColumnValues = $joinColumnValues;
            parent::__construct();
        }
        private function _load() {
            if ( ! $this->_loaded) {
                $this->_assoc->load($this->_owner, $this, $this->_em, $this->_joinColumnValues);
                unset($this->_em);
                unset($this->_owner);
                unset($this->_assoc);
                unset($this->_joinColumnValues);
                $this->_loaded = true;
            }
        }
        public function __isInitialized__() { return $this->_loaded; }

        
        public function setId($id) {
            $this->_load();
            return parent::setId($id);
        }

        public function getId() {
            $this->_load();
            return parent::getId();
        }

        public function setPhrase($phrase) {
            $this->_load();
            return parent::setPhrase($phrase);
        }

        public function getPhrase() {
            $this->_load();
            return parent::getPhrase();
        }

        public function setType(\kateglo\application\models\PhraseType $type) {
            $this->_load();
            return parent::setType($type);
        }

        public function getType() {
            $this->_load();
            return parent::getType();
        }

        public function setLexical(\kateglo\application\models\Lexical $lexical) {
            $this->_load();
            return parent::setLexical($lexical);
        }

        public function getLexical() {
            $this->_load();
            return parent::getLexical();
        }

        public function addDefinition(\kateglo\application\models\Definition $definition) {
            $this->_load();
            return parent::addDefinition($definition);
        }

        public function removeDefinition(\kateglo\application\models\Definition $definition) {
            $this->_load();
            return parent::removeDefinition($definition);
        }

        public function getDefinitions() {
            $this->_load();
            return parent::getDefinitions();
        }

        public function setProverbs(\kateglo\application\utilities\collections\ArrayCollection $proverbs) {
            $this->_load();
            return parent::setProverbs($proverbs);
        }

        public function getProverbs() {
            $this->_load();
            return parent::getProverbs();
        }

        public function setRelations(\kateglo\application\utilities\collections\ArrayCollection $relations) {
            $this->_load();
            return parent::setRelations($relations);
        }

        public function getRelations() {
            $this->_load();
            return parent::getRelations();
        }


        public function __sleep() {
            if (!$this->_loaded) {
                throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
            }
            return array('id', 'phrase', 'type', 'lexical', 'definitions', 'proverbs', 'relations');
        }
    }
}