<?php
namespace kateglo\proxies {
    /**
     * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
     */
    class kategloapplicationmodelsSyllabelProxy extends \kateglo\application\models\Syllabel implements \Doctrine\ORM\Proxy\Proxy {
        private $_entityPersister;
        private $_identifier;
        private $_loaded = false;
        public function __construct($entityPersister, $identifier) {
            $this->_entityPersister = $entityPersister;
            $this->_identifier = $identifier;
            
        }
        private function _load() {
            if ( ! $this->_loaded) {
                $this->_entityPersister->load($this->_identifier, $this);
                unset($this->_entityPersister);
                unset($this->_identifier);
                $this->_loaded = true;
            }
        }
        public function __isInitialized__() { return $this->_loaded; }

        
        public function setLemma(\kateglo\application\models\Lemma $lemma) {
            $this->_load();
            return parent::setLemma($lemma);
        }

        public function getLemma() {
            $this->_load();
            return parent::getLemma();
        }

        public function setSyllabel($syllabel) {
            $this->_load();
            return parent::setSyllabel($syllabel);
        }

        public function getSyllabel() {
            $this->_load();
            return parent::getSyllabel();
        }


        public function __sleep() {
            if (!$this->_loaded) {
                throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
            }
            return array('id', 'lemma', 'syllabel');
        }
    }
}