<?php
namespace kateglo\proxies {
    /**
     * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
     */
    class kategloapplicationmodelsLemmaProxy extends \kateglo\application\models\Lemma implements \Doctrine\ORM\Proxy\Proxy {
        private $_entityPersister;
        private $_identifier;
        private $_loaded = false;
        public function __construct($entityPersister, $identifier) {
            $this->_entityPersister = $entityPersister;
            $this->_identifier = $identifier;
            parent::__construct();
        }
        private function _load() {
            if ( ! $this->_loaded) {
                $this->_entityPersister->load($this->_identifier, $this);
                unset($this->_entityPersister);
                unset($this->_identifier);
                $this->_loaded = true;
            }
        }
        public function __isInitialized__() { return $this->_loaded; }

        
        public function getId() {
            $this->_load();
            return parent::getId();
        }

        public function setLemma($lemma) {
            $this->_load();
            return parent::setLemma($lemma);
        }

        public function getLemma() {
            $this->_load();
            return parent::getLemma();
        }

        public function setSyllabel(\kateglo\application\models\Syllabel $syllabel) {
            $this->_load();
            return parent::setSyllabel($syllabel);
        }

        public function getSyllabel() {
            $this->_load();
            return parent::getSyllabel();
        }

        public function addType(\kateglo\application\models\Type $type) {
            $this->_load();
            return parent::addType($type);
        }

        public function removeType(\kateglo\application\models\Type $type) {
            $this->_load();
            return parent::removeType($type);
        }

        public function getTypes() {
            $this->_load();
            return parent::getTypes();
        }

        public function addDefinition(\kateglo\application\models\Definition $definition) {
            $this->_load();
            return parent::addDefinition($definition);
        }

        public function removeDefinition(\kateglo\application\models\Definition $definition) {
            $this->_load();
            return parent::removeDefinition($definition);
        }

        public function getDefinitions() {
            $this->_load();
            return parent::getDefinitions();
        }

        public function addGlossary(\kateglo\application\models\Glossary $glossary) {
            $this->_load();
            return parent::addGlossary($glossary);
        }

        public function removeGlossary(\kateglo\application\models\Glossary $glossary) {
            $this->_load();
            return parent::removeGlossary($glossary);
        }

        public function getGlossaries() {
            $this->_load();
            return parent::getGlossaries();
        }

        public function addRelation(\kateglo\application\models\Relation $relation) {
            $this->_load();
            return parent::addRelation($relation);
        }

        public function removeRelation(\kateglo\application\models\Relation $relation) {
            $this->_load();
            return parent::removeRelation($relation);
        }

        public function getRelations() {
            $this->_load();
            return parent::getRelations();
        }


        public function __sleep() {
            if (!$this->_loaded) {
                throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
            }
            return array('id', 'lemma', 'syllabel', 'types', 'definitions', 'glossaries', 'relations');
        }
    }
}