<?php
namespace kateglo\proxies {
    /**
     * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
     */
    class kategloapplicationmodelsLexicalAProxy extends \kateglo\application\models\Lexical implements \Doctrine\ORM\Proxy\Proxy {
        private $_em;
        private $_assoc;
        private $_owner;
        private $_joinColumnValues;
        private $_loaded = false;
        public function __construct($em, $assoc, $owner, array $joinColumnValues) {
            $this->_em = $em;
            $this->_assoc = $assoc;
            $this->_owner = $owner;
            $this->_joinColumnValues = $joinColumnValues;
            parent::__construct();
        }
        private function _load() {
            if ( ! $this->_loaded) {
                $this->_assoc->load($this->_owner, $this, $this->_em, $this->_joinColumnValues);
                unset($this->_em);
                unset($this->_owner);
                unset($this->_assoc);
                unset($this->_joinColumnValues);
                $this->_loaded = true;
                $exports = get_object_vars($this);
				$this->id= $exports['id'];
				$this->lexical= $exports['lexical'];
				$this->abbreviation= $exports['abbreviation'];
				$this->definitions= $exports['definitions'];
                
            }
        }
        public function __isInitialized__() { return $this->_loaded; }

        
        public function getId() {
            $this->_load();
            return parent::getId();
        }

        public function setLexical($lexical) {
            $this->_load();
            return parent::setLexical($lexical);
        }

        public function getLexical() {
            $this->_load();
            return parent::getLexical();
        }

        public function setAbbreviation($abbreviation) {
            $this->_load();
            return parent::setAbbreviation($abbreviation);
        }

        public function getAbbreviation() {
            $this->_load();
            return parent::getAbbreviation();
        }

        public function getDefinitions() {
            $this->_load();
            return parent::getDefinitions();
        }

        public function addDefinition(\kateglo\application\models\Definition $definition) {
            $this->_load();
            return parent::addDefinition($definition);
        }

        public function removeDefinition(\kateglo\application\models\Definition $definition) {
            $this->_load();
            return parent::removeDefinition($definition);
        }


        public function __sleep() {
            if (!$this->_loaded) {
                throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
            }
            return array('id', 'lexical', 'abbreviation', 'definitions');
        }
        
    }
}