<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Insert title here</title>
</head>
<body>

<div>
	<form tal:attributes="action search/getFormAction; method search/getFormMethod" >
		<div>
			<input type="text" tal:attributes="name search/getFieldName; value search/getFieldValue"  />
			<input type="submit" tal:attributes="name search/getButtonName; value search/getButtonValue" />
		</div> 
	</form>
	<table border="1">
		<tr><td colspan="3" style="text-align: center; font-weight: bold; font-size: 14px;" tal:define="global getLemma lemma/getLemma; syllabel lemma/getSyllabel/getSyllabel">${getLemma} (${syllabel})</td></tr>
		<tr><td colspan="3" style="font-weight: bold">Types</td></tr>
		<tr tal:repeat="type lemma/getTypes"><td tal:content="type/getId">type id</td><td colspan="2" tal:content="type/getType">type</td></tr>
		<tr tal:condition="php: lemma.getRelations().count() GT 0"><td colspan="3" style="font-weight: bold">Relations</td></tr>
		<tr tal:repeat="relation lemma/getRelations">
			<td tal:content="relation/getType/getType">relation type</td>
			<td colspan="2">
				<a tal:attributes="href relation/getChild/getLemma" tal:content="relation/getChild/getLemma" />
			</td>
		</tr>
		<tr tal:condition="php: lemma.getDefinitions().count() GT 0" ><td colspan="3" style="font-weight: bold">Definitions</td></tr>
		<tr tal:repeat="definition lemma/getDefinitions">
			<td tal:content="definition/getLexical/getLexical">lexical</td>
			<td tal:condition="php: definition.getSources().count() GT 0" tal:content="definition/getDefinition">definition</td>
			<td tal:condition="php: definition.getSources().count() GT 0" tal:repeat="definitionSource definition/getSources"><a tal:attributes="href definitionSource/getUrl; target string:_blank" tal:content="definitionSource/getLabel" /></td>
			<td colspan="2" tal:condition="php: definition.getSources().count() EQ 0" tal:content="definition/getDefinition">definition</td>
		</tr>
		<tr tal:condition="php: lemma.getGlossaries().count() GT 0"><td colspan="3" style="font-weight: bold">Glossaries</td></tr>
		<tr tal:repeat="glossary lemma/getGlossaries">
			<td tal:content="glossary/getDiscipline/getDiscipline">discipline</td>
			<td tal:condition="php: glossary.getSources().count() GT 0" tal:define="global glossaryLocale glossary/getLocale/getLocale; glossaryText glossary/getGlossary">(${glossaryLocale}) ${glossaryText}</td>
			<td tal:condition="php: glossary.getSources().count() GT 0" ><a tal:attributes="href glossary/getSources/getUrl" tal:content="glossary/getGources/getLabel" /></td>
			<td colspan="2" tal:condition="php: glossary.getSources().count() EQ 0" tal:define="global glossaryLocale glossary/getLocale/getLocale; glossaryText glossary/getGlossary">(${glossaryLocale}) ${glossaryText}</td>
		</tr>
	</table>
</div>
</body>
</html>